@FlowAccount_Workshop_HostAddress = http://localhost:5086

### Create a product
POST {{FlowAccount_Workshop_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "ข้าวผัด",
  "sku": "FOOD001",
  "price": 45.00,
  "stock": 20,
  "category": "อาหาร"
}
